/*
 * Your license here
 *
 * If you don't need it, remove this file and edit MyMetricUI accordingly.
 */
package com.eleandro.gephi.plugin.searchpath.nodepair;

import javax.swing.JSpinner;

/**
 *
 * See http://wiki.gephi.org/index.php/HowTo_write_a_metric#Create_StatisticsUI
 *
 * @author José Eleandro Custódio
 */
public class SearchPathNodePairtPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchPathLinkCountPanel
     */
    public SearchPathNodePairtPanel() {
        initComponents();
    }

    public int getPathNumber() {
        return ((Number) spinner.getValue()).intValue();
    }

    public void setPathNumber(int value) {
        if (value > 0 && value < 11) {
            spinner.setValue(value);
        }
    }

    public int getMergePath() {
        return ((Number) spinnerMerge.getValue()).intValue();
    }

    public void setMergePath(int value) {
        if (value > 0 && value < 11) {
            spinnerMerge.setValue(value);
        }
    }
    
        public int getPathOnReport(){
        return getInt(spinnerPathOnReport);
    }
    
    public void setPathOnReport(int pathOnReport){
        this.spinnerPathOnReport.setValue(pathOnReport);
    }
    
    private int getInt(JSpinner spinner){
        return ((Number)spinner.getValue()).intValue();
    }

    /**
     * -----------------------------------------------------------
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        directedButtonGroup = new javax.swing.ButtonGroup();
        header = new org.jdesktop.swingx.JXHeader();
        spinner = new javax.swing.JSpinner();
        spinnerMerge = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        LbChoose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spinnerPathOnReport = new javax.swing.JSpinner();

        setPreferredSize(new java.awt.Dimension(456, 218));

        header.setDescription(org.openide.util.NbBundle.getMessage(SearchPathNodePairtPanel.class, "SearchPathNodePairtPanel.header.description")); // NOI18N
        header.setTitle(org.openide.util.NbBundle.getMessage(SearchPathNodePairtPanel.class, "SearchPathNodePairtPanel.header.title")); // NOI18N

        spinner.setModel(new javax.swing.SpinnerNumberModel(1, 0, 15, 1));

        spinnerMerge.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel5.setText(org.openide.util.NbBundle.getMessage(SearchPathNodePairtPanel.class, "SearchPathNodePairtPanel.jLabel5.text")); // NOI18N

        LbChoose.setText(org.openide.util.NbBundle.getMessage(SearchPathNodePairtPanel.class, "SearchPathNodePairtPanel.LbChoose.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(SearchPathNodePairtPanel.class, "SearchPathNodePairtPanel.jLabel2.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(SearchPathNodePairtPanel.class, "SearchPathNodePairtPanel.jLabel4.text")); // NOI18N

        spinnerPathOnReport.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbChoose)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spinnerMerge)
                    .addComponent(spinner)
                    .addComponent(spinnerPathOnReport))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbChoose)
                    .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinnerMerge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spinnerPathOnReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbChoose;
    private javax.swing.ButtonGroup directedButtonGroup;
    private org.jdesktop.swingx.JXHeader header;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner spinner;
    private javax.swing.JSpinner spinnerMerge;
    private javax.swing.JSpinner spinnerPathOnReport;
    // End of variables declaration//GEN-END:variables
}
